version: 0.2

phases:
  install:
   runtime-versions:
     php: 8.1
     docker: 23
  pre_build:
    commands:
      - echo Installing Docker
      - yum update -y
      - echo Installing SonarScanner and conducting SAST
      - docker run --rm --network=host  -e SONAR_HOST_URL="http://3.138.139.230:9000/"  -e SONAR_LOGIN="sqp_14864a772e36334a6dec083115c57efa16c4bddb" -v $(pwd)/$CODEBUILD_SRC_DIR sonarsource/sonar-scanner-cli
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
      - unzip sonar-scanner-cli-4.4.0.2170-linux.zip
      - mv sonar-scanner-4.4.0.2170-linux /opt/sonar-scanner
      - chmod -R 775 /opt/sonar-scanner
      #- cd $CODEBUILD_SRC_DIR
      - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=PMY-COSMETICS -Dsonar.host.url=http://3.138.139.230:9000  -Dsonar.token=sqp_14864a772e36334a6dec083115c57efa16c4bddb
      - echo "STATIC ANALYIS IS DONE PLEASE GO to http://3.142.246.193:9000 to get your report"  

  build:
    commands:
      - echo Deploying Code to WebServer
      - aws s3 cp s3://devopsbucketstoragecapstone/Keys/DevOps_Key.pem .
      - chmod 400 DevOps_Key.pem
      - scp -i DevOps_Key.pem -o StrictHostKeyChecking=no -r ./Web_Server/* ubuntu@3.144.137.149:./Web_Server
      - ssh -i DevOps_Key.pem ubuntu@3.144.137.149 'sudo ./copy_to_server.sh'
  
  post_build:
    commands:
      - echo Running ZAP Full Scan with Ajax Spider for conducting DAST
      - |
        set +e # disable the 'exit immediately on error' option
        docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable:2.12.0 zap-full-scan.py  -t http://3.144.137.149/index.php -c configfiles/tests.conf -d > report.txt
        if grep -q -E 'FAIL-NEW: [1-9]+' report.txt; then # check if any new failures were detected
          aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
          echo "BUILD FAILED AND THE LAST KNOWN STABLE STATE WAS RESTORED BECAUSE A CRITICAL VULNERABILITY WAS DETECTED. PLEASE LOOK AT THE LATEST REPORT FOR FURTHER ANALYSIS"
          ssh -i DevOps_Key.pem ubuntu@3.12.136.142 'sudo ./implement_rollback.sh'
          exit 0
        else
          aws s3 cp report.txt s3://devopsbucketstoragecapstone/Reports/OWASP_ZAP_Report_$(date +"%Y-%m-%d-%H-%M-%S").txt
          echo "BUILD WAS SUCCESFUL and all security standards are met and no critical vulnerabilities were detected"
          exit 0
        fi
        set -e
