version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - yum update -y

  build:
    commands:
      - echo Deploying Code to WebServer
      - aws s3 cp s3://devopsbucketstoragecapstone/Keys/DevOps_Key.pem .
      - chmod 400 DevOps_Key.pem
      - scp -i DevOps_Key.pem -o StrictHostKeyChecking=no -r ./Web_Server/* ubuntu@3.17.58.105:./Webserver
      - ssh -i DevOps_Key.pem ubuntu@3.17.58.105 'sudo ./copy_to_server.sh'

